// Planets
export const SELECT_PLANET = {
    ADD: 'SELECT_PLANET_ADD',
    REPLACE: 'SELECT_PLANET_REPLACE',
    RESET: 'SELECT_PLANET_RESET'
};

// Vehicles
export const VEHICLE = {
    ADD: 'VEHICLE_ADD',
    REPLACE: 'VEHICLE_REPLACE',
    RESET: 'VEHICLE_RESET'
};

export const FETCH_PLANETS = {
    BEGIN: "FETCH_PLANETS_BEGIN",
    SUCCESS: "FETCH_PLANETS_SUCCESS",
    FAILURE: "FETCH_PLANETS_FAILURE"
};

export const FETCH_VEHICLES = {
    BEGIN: "FETCH_VEHICLES_BEGIN",
    SUCCESS: "FETCH_VEHICLES_SUCCESS",
    FAILURE: "FETCH_VEHICLES_FAILURE"
};

export const FETCH_TOKEN = {
    BEGIN: "FETCH_TOKEN_BEGIN",
    SUCCESS: "FETCH_TOKEN_BEGIN",
    FAILURE: "FETCH_TOKEN_FAILURE"
};

export const FIND = {
    BEGIN: "FIND_BEGIN",
    SUCCESS: "FIND_SUCCESS",
    FAILURE: "FIND_FAILURE"
};